/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;

import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Fernando
 */
public class ReadyBingoScreen extends javax.swing.JFrame {


    /**
     * Creates new form PreparedBingoScreen
     */
    public ReadyBingoScreen() {
        initComponents();
        setLocationRelativeTo(null);
        bNo.setSelected(true);
        areaReady.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bYes = new javax.swing.JToggleButton();
        bNo = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaReady = new javax.swing.JTextArea();
        contador = new javax.swing.JLabel();
        COUNTDOWN = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ready?");
        setMinimumSize(new java.awt.Dimension(409, 181));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Are you ready to play?");

        bYes.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bYes.setText("YES");
        bYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bYesActionPerformed(evt);
            }
        });

        bNo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bNo.setText("NO");
        bNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNoActionPerformed(evt);
            }
        });

        areaReady.setColumns(20);
        areaReady.setRows(5);
        jScrollPane1.setViewportView(areaReady);

        contador.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        contador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contador.setText("30");

        COUNTDOWN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        COUNTDOWN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        COUNTDOWN.setText("<html> COUNTDOWN<br> START GAME</html>");
        COUNTDOWN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(COUNTDOWN)
                            .addComponent(contador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bNo))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addComponent(COUNTDOWN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bYes)
                        .addComponent(bNo))
                    .addComponent(contador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bYesActionPerformed
        if (bNo.isSelected()) {
            bNo.setSelected(false);
            isReady();
        }
        bYes.setSelected(true);
    }//GEN-LAST:event_bYesActionPerformed

    private void bNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNoActionPerformed
        if (bYes.isSelected()) {
            bYes.setSelected(false);
            noReady();
        }
        bNo.setSelected(true);

    }//GEN-LAST:event_bNoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (bYes.isSelected()) {
            noReady();
        }
    }//GEN-LAST:event_formWindowClosing

    private void noReady() {
        Client.jsonSend.put("STATUS", "falha");
        Client.jsonSend.put("LISTACLIENTE", null);
        Client.jsonSend.put("MSG", null);
        Client.jsonSend.put("NOME", Client.username);
        Client.jsonSend.put("COD", "pronto");
        try {
            Client.buffWr.write(Client.jsonSend.toString() + "\r\n");
            Client.buffWr.flush();
            System.out.println("SEND: " + Client.jsonSend.toString());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error connect to server...", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void isReady() {
        Client.jsonSend.put("STATUS", "sucesso");
        Client.jsonSend.put("LISTACLIENTE", null);
        Client.jsonSend.put("MSG", null);
        Client.jsonSend.put("NOME", Client.username);
        Client.jsonSend.put("COD", "pronto");
        try {
            Client.buffWr.write(Client.jsonSend.toString() + "\r\n");
            Client.buffWr.flush();
            System.out.println("SEND: " + Client.jsonSend.toString());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error connect to server...", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel COUNTDOWN;
    public static javax.swing.JTextArea areaReady;
    private javax.swing.JToggleButton bNo;
    private javax.swing.JToggleButton bYes;
    public static javax.swing.JLabel contador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
